package com.kaikeventura.petgram.service;

import com.kaikeventura.petgram.domain.Pet;
import com.kaikeventura.petgram.domain.User;
import com.kaikeventura.petgram.dto.PetRequest;
import com.kaikeventura.petgram.dto.PetResponse;
import com.kaikeventura.petgram.repository.PetRepository;
import com.kaikeventura.petgram.repository.UserRepository;
import com.kaikeventura.petgram.service.mappers.PetMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PetService {

    private final PetRepository petRepository;
    private final UserRepository userRepository;
    private final PetMapper petMapper;

    @Transactional
    public PetResponse createPet(PetRequest petRequest) {
        var owner = getCurrentUser();
        var pet = new Pet(
                null, // ID will be generated by JPA
                petRequest.name(),
                petRequest.breed(),
                petRequest.birthDate(),
                owner,
                null, // createdAt will be generated
                null  // updatedAt will be generated
        );

        var savedPet = petRepository.save(pet);
        return petMapper.toPetResponse(savedPet);
    }

    @Transactional(readOnly = true)
    public List<PetResponse> findMyPets() {
        var owner = getCurrentUser();
        return petRepository.findByOwner(owner).stream()
                .map(petMapper::toPetResponse)
                .collect(Collectors.toList());
    }

    private User getCurrentUser() {
        var principal = (org.springframework.security.core.userdetails.User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        var userId = UUID.fromString(principal.getUsername());
        return userRepository.findById(userId)
                .orElseThrow(() -> new IllegalStateException("User not found"));
    }
}
